from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Sequence

from .dataset import ROOT, discover_nanomart, manifest_summary


OUTPUT_DIR = ROOT / "ENGINE_REBUILD" / "formula_research"


def _write_manifest() -> dict:
    records = discover_nanomart()
    summary = manifest_summary(records)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    json_path = OUTPUT_DIR / "nanomart_manifest.json"
    json_path.write_text(
        json.dumps(
            {"summary": summary, "records": [r.to_dict() for r in records]},
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )

    csv_path = OUTPUT_DIR / "nanomart_manifest.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "report_id",
                "source_file",
                "included",
                "exclusion_reason",
                "duplicate_of",
                "schema",
                "timestamp",
                "attacker",
                "defender",
                "winner",
                "turns",
                "turns_min",
                "turns_max",
                "assumptions",
                "warnings",
            ]
        )
        for record in records:
            writer.writerow(
                [
                    record.report_id,
                    record.source_file,
                    record.included,
                    record.exclusion_reason or "",
                    record.duplicate_of or "",
                    record.schema,
                    record.timestamp or "",
                    f"{record.attacker.troops} T{record.attacker.tier} {record.attacker.troop_class}",
                    f"{record.defender.troops} T{record.defender.tier} {record.defender.troop_class}",
                    record.winner,
                    record.turns if record.turns is not None else "",
                    record.turns_min if record.turns_min is not None else "",
                    record.turns_max if record.turns_max is not None else "",
                    " | ".join(record.assumptions),
                    " | ".join(record.warnings),
                ]
            )

    md_path = OUTPUT_DIR / "NANOMART_MANIFEST.md"
    lines = [
        "# Canonical NanoMart Manifest",
        "",
        "Generated by `py -m wos_sim.formula_research manifest`. Source JSON files are read-only.",
        "",
        f"- Discovered: {summary['discovered']}",
        f"- Included canonical fixtures: {summary['included']}",
        f"- Excluded: {summary['excluded']}",
        f"- Included with turn evidence: {summary['included_with_turn_evidence']}",
        f"- Included without turn evidence: {summary['included_without_turn_evidence']}",
        f"- Exact duplicate artifacts: {summary['duplicate_artifacts']}",
        "",
        "| Report | Included | Duplicate of | Matchup | Winner | Turns | Reason / assumptions |",
        "|---|---|---|---|---|---|---|",
    ]
    for record in records:
        turns = (
            str(record.turns)
            if record.turns is not None
            else (
                f"{record.turns_min}-{record.turns_max}"
                if record.turns_min is not None
                else "not captured"
            )
        )
        reason = record.exclusion_reason or "; ".join(record.assumptions) or "none"
        lines.append(
            "| "
            + " | ".join(
                [
                    record.report_id,
                    "yes" if record.included else "no",
                    record.duplicate_of or "",
                    f"{record.attacker.troops} T{record.attacker.tier} {record.attacker.troop_class} vs "
                    f"{record.defender.troops} T{record.defender.tier} {record.defender.troop_class}",
                    record.winner,
                    turns,
                    reason.replace("|", "\\|"),
                ]
            )
            + " |"
        )
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return summary


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("manifest", help="normalize and inventory NanoMart fixtures")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "manifest":
        summary = _write_manifest()
        print(json.dumps(summary, indent=2))
        return 0 if summary["included"] == 70 else 2
    raise AssertionError(args.command)

